version: '3'

tasks:
  package:update:
    desc: Generates Package.swift from the template using a given tag and checksum.
    # We prefix with "RELEASE_" to avoid clashing with Taskfile's internal env value, "CHECKSUM".
    cmds:
      - go run tasks/package_update.go "{{.RELEASE_TAG}}" "{{.RELEASE_CHECKSUM}}"
      - mvn versions:set -DnewVersion="{{.RELEASE_TAG}}-SNAPSHOT" -DgenerateBackupPoms=false
    sources:
      - tasks/package_update.go
      - Package.swift.template
    generates:
      - Package.swift
      - pom.xml
  
  package:publish:
    desc: Publishes the updated Package.swift and a new git tag.
    cmds:
      - git config --global user.name 'github-actions[bot]'
      - git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - git add Package.swift
      - git add pom.xml
      - git commit -m "Update Package.swift and pom.xml for release {{.RELEASE_TAG}}"
      - git tag -a "{{.RELEASE_TAG}}" -m "Release {{.RELEASE_TAG}}"
      - git push origin HEAD:main
      - git push origin "{{.RELEASE_TAG}}"
    sources:
      - Package.swift

  build:mobileproxy:
    desc: Builds the mobileproxy artifacts from the Outline SDK.
    cmds:
      - git clone --depth 1 --branch "{{.OUTLINE_SDK_TAG}}" https://github.com/Jigsaw-Code/outline-sdk.git outline-sdk
      - cd outline-sdk/x && task build:mobileproxy
      - mkdir -p output
      - cp outline-sdk/x/out/mobileproxy/mobileproxy.aar output/mobileproxy.aar
      - cp outline-sdk/x/out/mobileproxy/mobileproxy.xcframework.zip output/mobileproxy.xcframework.zip
      - rm -rf outline-sdk
    generates:
      - output/mobileproxy.aar
      - output/mobileproxy.xcframework.zip
